sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
before_script:
  - npm prune
